### ISSUE TITLE
SiteID = NA  causes hanging errors

### ISSUE THREAD

**Issue by sebsfox** [kehraProject/r_rdefra#6] opened 2017-06-09 09:12 UTC
Hi - the package is great. Thanks for making it available.

I get errors with most functions when I include sites where SiteID = NA, eg:

```
library(rdefra)
stations_raw <- ukair_catalogue()
stations <- ukair_get_coordinates(stations_raw)
```
Gives the following error:
Error in curl::curlfetchmemory(url, handle = handle) : Failure when receiving data from the peer

Though the following works instantly:

```
library(rdefra)
stations_raw <- ukair_catalogue()
stations <- ukair_get_coordinates(stations_raw[!is.na(stations_raw$EMEP.Site.ID),])
```
Thanks

**Comment by cvitolo** [comment] 2018-07-28 20:11
The problem seems to be with the number of requests sent to the server, not with NAs.
Your second example (that works) you are sending less than 1000 requests.
In your first example you are sending more than 1000 requests, which causes the server to fail.

I have temporarily disabled http2, as explained [here](https://github.com/ropensci/monkeylearn/pull/15).

Now your first example works, although NAs might be generated by coercion.

I'm closing this as the issue is resolved. Thanks for reporting it!

**Closed as completed by cvitolo** 2018-07-28 20:11 UTC
