### ISSUE TITLE
Different variables for ukair_get_coordinates() when inputs are fed in differently

### ISSUE THREAD

**Issue by sebsfox** [kehraProject/r_rdefra#7] opened 2017-06-09 09:20 UTC
Hi there,

Depending on how I feed the Site ID into the function `ukair_get_coordinates()` I get a data.frame of different width. Two methods are as follows:

**Set up**
```
library('rdefra')
stations_raw <- ukair_catalogue()
```

**Method 1**
```
stations <- data.frame()
for (i in stations_raw$UK.AIR.ID[!is.na(stations_raw$EMEP.Site.ID)]){
        stations <- rbind(stations, ukair_get_coordinates(i))
}
```

**Method 2**
```
stations_raw <- ukair_catalogue()
stations_all <- ukair_get_coordinates(stations_raw[!is.na(stations_raw$EMEP.Site.ID),])
```

Method 1 returns a data.frame with 5 variables, and Method 2 returns a data.frame with 16 variables (and Eastings and Northings are generally incomplete).

Thank you

**Comment by cvitolo** [comment] 2018-07-28 20:19
Hi @sebsfox!
The function ukair_get_coordinates(), as the name suggests, only tries to get the coordinates for the stations ids. 
If you feed ukair_get_coordinates() with a character vector containing only identification numbers, you get a data.frame with identification numbers and coordinates.
If you feed ukair_get_coordinates() with a dataframe containing a column with identification numbers, you get the same data.frame in which missing coordinates have been infilled (if available).

Of course you might still get NAs, this happens for stations that do not have coordinates available of the relevant ukair webpage.

Hope this clarifies everything.

I'm closing this issue, as this is the intended behaviour.

**Closed as completed by cvitolo** 2018-07-28 20:19 UTC
